Update Dockerfile URL and comment out auto-tests

diff --git a/.github/workflows/platform-ci.yml b/.github/workflows/platform-ci.yml
--- a/.github/workflows/platform-ci.yml
+++ b/.github/workflows/platform-ci.yml
@@ -189,7 +189,7 @@ jobs:
       with:
         tag: ${{ env.DOCKER_TAG }}
         imageName: 'platform'
-        dockerFiles: 'https://raw.githubusercontent.com/VirtoCommerce/vc-docker/feat/net10/linux/platform/Dockerfile;https://raw.githubusercontent.com/VirtoCommerce/vc-docker/master/linux/platform/wait-for-it.sh'
+        dockerFiles: 'https://raw.githubusercontent.com/VirtoCommerce/vc-docker/VCST-6126/linux/platform/Dockerfile;https://raw.githubusercontent.com/VirtoCommerce/vc-docker/master/linux/platform/wait-for-it.sh'
 
     - name: Docker Login
       if: ${{ env.BUILD_DOCKER == 'true' }}
@@ -316,79 +316,79 @@ jobs:
       if: success()
       run: |
         echo "Jira Upload Build Info response: ${{ steps.push_build_info_to_jira.outputs.response }}"
-  auto-tests:
-    needs: ci
-    if: ${{ ((github.ref == 'refs/heads/dev') && (github.event_name == 'push') && (needs.ci.outputs.run-e2e == 'true')) ||
-        (github.event_name == 'workflow_dispatch') || (github.base_ref == 'dev') && (github.event_name == 'pull_request') }}
-    uses: VirtoCommerce/.github/.github/workflows/pytest-tests.yml@v3.1000.1
-    with:
-      installModules: 'true'
-      installCustomModule: 'false'
-      platformDockerTag: ${{ needs.ci.outputs.tag }}
-      vctestingRepoBranch: 'dev'
-      frontendZipUrl: 'latest'
-      testSuites: 'graphql,restapi,e2e'
-    secrets:
-      envPAT: ${{ secrets.REPO_TOKEN }}
-      testSecretEnvFile: ${{ secrets.VC_TESTING_MODULE_ENV_FILE }}
-      sendgridApiKey: ${{ secrets.SENDGRID_APIKEY_4E2E_AUTOTESTS }}
-      appInsightsInstrumentationKey: ${{ secrets.E2E_APPINSIGHTSINSTRUMENTATIONKEY }}
+  # auto-tests:
+  #   needs: ci
+  #   if: ${{ ((github.ref == 'refs/heads/dev') && (github.event_name == 'push') && (needs.ci.outputs.run-e2e == 'true')) ||
+  #       (github.event_name == 'workflow_dispatch') || (github.base_ref == 'dev') && (github.event_name == 'pull_request') }}
+  #   uses: VirtoCommerce/.github/.github/workflows/pytest-tests.yml@v3.1000.1
+  #   with:
+  #     installModules: 'true'
+  #     installCustomModule: 'false'
+  #     platformDockerTag: ${{ needs.ci.outputs.tag }}
+  #     vctestingRepoBranch: 'dev'
+  #     frontendZipUrl: 'latest'
+  #     testSuites: 'graphql,restapi,e2e'
+  #   secrets:
+  #     envPAT: ${{ secrets.REPO_TOKEN }}
+  #     testSecretEnvFile: ${{ secrets.VC_TESTING_MODULE_ENV_FILE }}
+  #     sendgridApiKey: ${{ secrets.SENDGRID_APIKEY_4E2E_AUTOTESTS }}
+  #     appInsightsInstrumentationKey: ${{ secrets.E2E_APPINSIGHTSINSTRUMENTATIONKEY }}
 
-  swagger-validation:
-    if: ${{ ((github.ref == 'refs/heads/dev') && (github.event_name == 'push')) ||
-        (github.event_name == 'workflow_dispatch') || ((github.base_ref == 'dev') && (github.event_name == 'pull_request')) }}
-    needs: ci
-    runs-on: ubuntu-24.04
-    permissions:
-      contents: read
-      packages: read
-    env:
-      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
-      DOCKER_TAG: ${{ needs.ci.outputs.tag }}
-      PACKAGE_SERVER: 'ghcr.io'
-    steps:
-      - name: Install VirtoCommerce.GlobalTool
-        uses: VirtoCommerce/.github/actions/setup-vcbuild@v3.1000.1
+  # swagger-validation:
+  #   if: ${{ ((github.ref == 'refs/heads/dev') && (github.event_name == 'push')) ||
+  #       (github.event_name == 'workflow_dispatch') || ((github.base_ref == 'dev') && (github.event_name == 'pull_request')) }}
+  #   needs: ci
+  #   runs-on: ubuntu-24.04
+  #   permissions:
+  #     contents: read
+  #     packages: read
+  #   env:
+  #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
+  #     DOCKER_TAG: ${{ needs.ci.outputs.tag }}
+  #     PACKAGE_SERVER: 'ghcr.io'
+  #   steps:
+  #     - name: Install VirtoCommerce.GlobalTool
+  #       uses: VirtoCommerce/.github/actions/setup-vcbuild@v3.1000.1
 
-      - name: Swagger validation
-        uses: VirtoCommerce/.github/actions/docker-env@v3.1000.1
-        with:
-          appInsightsInstrumentationKey: ${{ secrets.E2E_APPINSIGHTSINSTRUMENTATIONKEY }}
-          githubUser: ${{ github.actor }}
-          githubToken: ${{ env.GITHUB_TOKEN }}
-          platformDockerTag: ${{ env.DOCKER_TAG }}
-          platformImage: ${{ env.PACKAGE_SERVER }}/virtocommerce/platform
-          installSampleData: 'false'
+  #     - name: Swagger validation
+  #       uses: VirtoCommerce/.github/actions/docker-env@v3.1000.1
+  #       with:
+  #         appInsightsInstrumentationKey: ${{ secrets.E2E_APPINSIGHTSINSTRUMENTATIONKEY }}
+  #         githubUser: ${{ github.actor }}
+  #         githubToken: ${{ env.GITHUB_TOKEN }}
+  #         platformDockerTag: ${{ env.DOCKER_TAG }}
+  #         platformImage: ${{ env.PACKAGE_SERVER }}/virtocommerce/platform
+  #         installSampleData: 'false'
 
-  deploy-cloud:
-    if: ${{ !failure() && !cancelled() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
-    needs:
-      - ci
-      - swagger-validation
-    uses: VirtoCommerce/.github/.github/workflows/deploy-cloud.yml@v3.1000.1
-    with:
-      releaseSource: platform
-      platformVer: ${{ needs.ci.outputs.version }}
-      platformTag: ${{ needs.ci.outputs.tag }}
-      jiraKeys: ${{ needs.ci.outputs.jira-keys }}
-      matrix: '{"include":${{ needs.ci.outputs.matrix }}}'
-    secrets: inherit
+  # deploy-cloud:
+  #   if: ${{ !failure() && !cancelled() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
+  #   needs:
+  #     - ci
+  #     - swagger-validation
+  #   uses: VirtoCommerce/.github/.github/workflows/deploy-cloud.yml@v3.1000.1
+  #   with:
+  #     releaseSource: platform
+  #     platformVer: ${{ needs.ci.outputs.version }}
+  #     platformTag: ${{ needs.ci.outputs.tag }}
+  #     jiraKeys: ${{ needs.ci.outputs.jira-keys }}
+  #     matrix: '{"include":${{ needs.ci.outputs.matrix }}}'
+  #   secrets: inherit
 
-  owasp-scan:
-    if: ${{ github.ref == 'refs/heads/dev' && github.event_name == 'push' }}
-    runs-on: ubuntu-latest
-    needs: 
-      - deploy-cloud
-    steps:
-      - name: OWASP ZAP Full Scan
-        uses: zaproxy/action-baseline@de8ad967d3548d44ef623df22cf95c3b0baf8b25 # v0.15.0
-        with:
-          token: ${{ secrets.REPO_TOKEN }}
-          target: 'https://vcptcore-dev.govirto.com'
-          cmd_options: '-a -d'
+  # owasp-scan:
+  #   if: ${{ github.ref == 'refs/heads/dev' && github.event_name == 'push' }}
+  #   runs-on: ubuntu-latest
+  #   needs: 
+  #     - deploy-cloud
+  #   steps:
+  #     - name: OWASP ZAP Full Scan
+  #       uses: zaproxy/action-baseline@de8ad967d3548d44ef623df22cf95c3b0baf8b25 # v0.15.0
+  #       with:
+  #         token: ${{ secrets.REPO_TOKEN }}
+  #         target: 'https://vcptcore-dev.govirto.com'
+  #         cmd_options: '-a -d'
 
   trivy-scan:
-    if: ${{ github.ref == 'refs/heads/dev' && github.event_name == 'push' }}
+    # if: ${{ github.ref == 'refs/heads/dev' && github.event_name == 'push' }}
     needs: 'ci'
     uses: VirtoCommerce/.github/.github/workflows/docker-image-vulnerability-process.yml@v3.1000.1
     with:
